package entity;
// Generated 17/10/2019 05:16:23 PM by Hibernate Tools 4.3.1
// Genera el pojo. Este archivo es un clase java que implementa serializable. 
// El archivo es un reflejo de la tabla de la base de datos. 
// Tiene sus getters y setters



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer idUser;
     private String id;
     private String password;

    public Users() {
    }

    public Users(String id, String password) {
       this.id = id;
       this.password = password;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


